-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 03-10-2022 a las 04:09:34
-- Versión del servidor: 10.4.24-MariaDB
-- Versión de PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `pokemones`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `pokemon`
--

CREATE TABLE `pokemon` (
  `id` int(11) NOT NULL,
  `numero` int(11) NOT NULL,
  `imagen` varchar(100) NOT NULL,
  `nombre` varchar(100) NOT NULL,
  `tipo` varchar(100) NOT NULL,
  `descripcion` varchar(8000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `pokemon`
--

INSERT INTO `pokemon` (`id`, `numero`, `imagen`, `nombre`, `tipo`, `descripcion`) VALUES
(4, 1, 'Bulbasaur.png', 'Bulbasaur', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(5, 2, 'Ivysaur.png', 'Ivysaur', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(6, 3, 'Venusaur.png', 'Venusaur', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(7, 4, 'Charmander.png', 'Charmander', 'fuego.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(8, 5, 'Charmeleon.png', 'Charmeleon', 'fuego.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(9, 6, 'Charizard.png', 'Charizard', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(10, 7, 'Squirtle.png', 'Squirtle', 'agua.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(11, 8, 'Wartortle.png', 'Wartortle', 'agua.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(12, 9, 'Blastoise.png', 'Blastoise', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(13, 10, 'Caterpie.png', 'Caterpie', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(14, 11, 'Metapod.png', 'Metapod', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(15, 12, 'Butterfree.png', 'Butterfree', 'veneno.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(16, 13, 'Weedle.png', 'Weedle', 'veneno.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(17, 14, 'Kakuna.png', 'Kakuna', 'veneno.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(18, 15, 'Beedrill.png', 'Beedrill', 'veneno.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(19, 16, 'Pidgey.png', 'Pnumerogey', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(20, 17, 'Pidgeotto.png', 'Pnumerogeotto', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(21, 18, 'Pidgeot.png', 'Pnumerogeot', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(22, 19, 'Rattata.png', 'Rattata', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.'),
(23, 20, 'Raticate.png', 'Raticate', 'tierra.png', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum bibendum quam ultrices maximus. Mauris lobortis ex eget arcu ornare laoreet. Sed non ullamcorper enim. Donec condimentum massa bibendum accumsan sagittis. In non tellus sodales, semper justo et, molestie magna. Suspendisse feugiat tempor dui, at malesuada massa porttitor sed. Donec vitae euismod augue, sed iaculis diam. Nam tempus odio sit amet enim hendrerit, eget ultrices nisi tincidunt.\r\n\r\nMaecenas non tortor eleifend, tempor ante vitae, vulputate augue. Aenean sodales suscipit quam, dictum pharetra velit imperdiet nec. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum tincidunt ornare malesuada. Etiam imperdiet scelerisque sapien, nec efficitur lacus luctus ac. Aliquam vel rhoncus nunc. Maecenas ultrices neque erat, at suscipit ligula eleifend convallis. Nam nibh felis, dapibus sit amet urna sed, congue tempus dui. Aliquam a felis arcu. Praesent ac enim et sapien auctor suscipit sit amet id massa. Donec mollis imperdiet turpis vitae tincidunt. In ornare orci tortor, et iaculis enim auctor nec. Nulla id efficitur dui, sed mollis felis. Quisque ullamcorper neque vel sem rhoncus, dignissim blandit odio molestie. Aenean non dolor nibh. Mauris facilisis ac lorem eget tincidunt.\r\n\r\nUt justo neque, dapibus vitae placerat sed, dignissim sit amet nunc. Integer feugiat vitae augue non varius. Ut faucibus tellus sit amet ante tempus, in pharetra nunc venenatis. Cras ut tristique enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus dolor est, mollis sed est et, scelerisque venenatis nibh. Curabitur cursus, urna eu semper fringilla, augue enim hendrerit.');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `usuario`
--

CREATE TABLE `usuario` (
  `Id` int(11) NOT NULL,
  `Nombre` varchar(50) NOT NULL,
  `Password` varchar(50) NOT NULL,
  `Administrador` bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `usuario`
--

INSERT INTO `usuario` (`Id`, `Nombre`, `Password`, `Administrador`) VALUES
(1, 'Fer', '1234', b'0'),
(2, 'Eve', '1234', b'1'),
(3, 'Juan', '1234', b'1'),
(4, 'Tomas', '1234', b'1'),
(5, 'Sofia', '1234', b'1');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `pokemon`
--
ALTER TABLE `pokemon`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `numero` (`numero`);

--
-- Indices de la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`Id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `pokemon`
--
ALTER TABLE `pokemon`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- AUTO_INCREMENT de la tabla `usuario`
--
ALTER TABLE `usuario`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
